import { useState, useEffect, useCallback } from 'react';
import { useGitHub } from '@/hooks/useGitHub';
import { useCodeReview } from '@/hooks/useCodeReview';
import { useAIReview } from '@/hooks/useAIReview';
import { PullRequest, SonarQubeResults, AIReviewResult, ReviewCommand } from '@/types/codeReview';
import { GitHubConfigPanel } from '@/components/dashboard/GitHubConfigPanel';
import { AIConfigPanel } from '@/components/dashboard/AIConfigPanel';
import { PRList } from '@/components/dashboard/PRList';
import { PRDetailPanel } from '@/components/dashboard/PRDetailPanel';
import { SonarResultsPanel } from '@/components/dashboard/SonarResultsPanel';
import { AIReviewPanel } from '@/components/dashboard/AIReviewPanel';
import { ThresholdConfigPanel } from '@/components/dashboard/ThresholdConfigPanel';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  Settings, 
  Github, 
  Shield, 
  Sparkles, 
  Moon, 
  Sun,
  Webhook,
  Code2,
  GitMerge,
  MessageSquare
} from 'lucide-react';
import { toast } from '@/hooks/use-toast';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { shouldAutoMerge, decisionReason, AutoMergeConfig } from '@/lib/autoMerge';
import { saveHistory } from '@/lib/autoMergeHistory';

export default function Dashboard() {
  const { 
    config, 
    setConfig, 
    pullRequests, 
    isLoading, 
    fetchPullRequests, 
    fetchPRFiles,
    testConnection,
    postPRComment,
    mergePR
  } = useGitHub();
  
  const { 
    thresholds, 
    setThresholds, 
    analyzePR, 
    mockSonarResults,
    isAnalyzing,
    analysisProgress 
  } = useCodeReview();

  const {
    aiConfig,
    setAIConfig,
    generateReview,
    isGenerating: isGeneratingAI
  } = useAIReview();

  const [selectedPR, setSelectedPR] = useState<PullRequest | null>(null);
  const [sonarResults, setSonarResults] = useState<SonarQubeResults | null>(null);
  const [aiReview, setAIReview] = useState<AIReviewResult | null>(null);
  const [junitScore, setJUnitScore] = useState<number | null>(null);
  const [isDark, setIsDark] = useState(() => {
    if (typeof window !== 'undefined') {
      return document.documentElement.classList.contains('dark');
    }
    return true;
  });

  useEffect(() => {
    if (isDark) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [isDark]);

  useEffect(() => {
    if (config) {
      fetchPullRequests();
    }
  }, [config, fetchPullRequests]);

  const handleSelectPR = useCallback((pr: PullRequest) => {
    setSelectedPR(pr);
    setSonarResults(null);
    setAIReview(null);
  }, []);

  const formatReviewAsMarkdown = (review: AIReviewResult, pr: PullRequest): string => {
    const suggestions = review.suggestions
      .map(s => `- **[${s.severity.toUpperCase()}]** ${s.message}\n  - File: \`${s.file}\`${s.line ? ` (line ${s.line})` : ''}\n  - ${s.suggestion}`)
      .join('\n\n');

    return `## 🤖 AI Code Review for PR #${pr.number}

### Overall Score: ${review.overallScore}/100

### Category Scores
| Category | Score |
|----------|-------|
| Code Quality | ${review.categories.codeQuality}% |
| Security | ${review.categories.security}% |
| Performance | ${review.categories.performance}% |
| Maintainability | ${review.categories.maintainability}% |
| Testability | ${review.categories.testability}% |

### Summary
${review.summary}

### Suggestions
${suggestions || 'No specific suggestions.'}

---
*Generated by ${review.model} at ${new Date(review.timestamp).toLocaleString()}*`;
  };

  const handleRunAnalysis = useCallback(async () => {
    if (!selectedPR) return;

    const files = await fetchPRFiles(selectedPR.number);
    await analyzePR(selectedPR, files);
    
    // Generate SonarQube results
    const results = mockSonarResults(selectedPR);
    setSonarResults(results);
    
    // Generate AI review with actual code diff
    const review = await generateReview(selectedPR, files, { type: 'review', prNumber: selectedPR.number });
    
    if (review) {
      setAIReview(review);

      // Determine auto-merge behavior based on configurable AI & Sonar thresholds.
      // Assumptions made:
      // - AI overall score is 0-100 (higher is better).
      // - Sonar metric used for the decision is `issuesSummary.total` (lower is better).
      // - `aiConfig.autoMergeMode === 'less'` means auto-merge when BOTH values are less than thresholds.
      //   `autoMergeMode === 'greater'` means auto-merge when BOTH values are greater than thresholds.
      // These choices are configurable via AI settings (defaults set in types).

      const aiScore = review.overallScore;
      const sonarIssues = results?.issuesSummary?.total ?? Infinity;

      const cfg: AutoMergeConfig = {
        enabled: !!aiConfig.autoMergeEnabled,
        mode: aiConfig.autoMergeMode || 'less',
        aiThreshold: aiConfig.autoMergeThresholdAI ?? 70,
        sonarThreshold: aiConfig.autoMergeThresholdSonar ?? 5,
      };

      // Detect if Java files are present in the PR and compute a simple JUnit score heuristic.
  const hasJava = files.some(f => f.filename.endsWith('.java'));
      // Heuristic: if the PR includes test files in typical Java test paths, give a high junitScore;
      // otherwise 0. This is a lightweight approximation since we can't run tests here.
      const junitTestPatterns = ['/src/test/java/', '/test/java/', '/src/main/java/'];
      const hasJUnitTestsInPR = files.some(f => junitTestPatterns.some(p => f.filename.includes(p)));
  const junitScore = hasJava ? (hasJUnitTestsInPR ? 90 : 0) : 100;
  // store computed junit score for diagnostics
  setJUnitScore(junitScore);

      const willMergeBase = shouldAutoMerge(aiScore, sonarIssues, cfg);
      const reasonBase = decisionReason(aiScore, sonarIssues, cfg);

      // If Java files present and the feature is enabled, require junit score threshold as well
      const junitThreshold = aiConfig.autoMergeThresholdJUnit ?? 70;
      const requireJUnit = !!aiConfig.requireJUnitForJava;
      
      // Properly handle Java/JUnit requirement
      let finalWillMerge = false;
      let junitReason = '';
      if (cfg.enabled) {
        if (hasJava && requireJUnit) {
          // Java files present and JUnit required: need both base decision AND junit score
          finalWillMerge = willMergeBase && junitScore >= junitThreshold;
          junitReason = `; Java detected, JUnit required: junitScore=${junitScore} >= ${junitThreshold} => ${junitScore >= junitThreshold}`;
        } else {
          // Either no Java files, or JUnit not required: just check base decision
          finalWillMerge = willMergeBase;
          junitReason = `; hasJava=${hasJava}, requireJUnit=${requireJUnit}`;
        }
      }

      // Save decision to history (localStorage)
      try {
        saveHistory(selectedPR.number, {
          timestamp: new Date().toISOString(),
          aiScore,
          sonarIssues,
          mode: cfg.mode,
          aiThreshold: cfg.aiThreshold,
          sonarThreshold: cfg.sonarThreshold,
          decision: finalWillMerge ? 'will_merge' : (cfg.enabled ? 'will_not_merge' : 'disabled'),
          details: `${reasonBase}${junitReason}; cfgEnabled=${cfg.enabled}`,
        });
      } catch (e) {
        console.error('Failed to save auto-merge history', e);
      }

      if (finalWillMerge) {
        toast({
          title: 'Auto-Merge Triggered',
          description: 'Configured thresholds met. Attempting to merge...',
        });
        console.log(`[AUTO-MERGE] ✅ MERGING PR #${selectedPR.number}: cfg.enabled=${cfg.enabled}, finalWillMerge=${finalWillMerge}`);
        console.log(`  → aiScore=${aiScore} (threshold ${cfg.aiThreshold}), sonarIssues=${sonarIssues} (threshold ${cfg.sonarThreshold}), mode=${cfg.mode}`);
        console.log(`  → ${reasonBase}`);
        const merged = await mergePR(selectedPR.number, selectedPR.title);
        // update history with result
        saveHistory(selectedPR.number, {
          timestamp: new Date().toISOString(),
          aiScore,
          sonarIssues,
          mode: cfg.mode,
          aiThreshold: cfg.aiThreshold,
          sonarThreshold: cfg.sonarThreshold,
          decision: merged ? 'merged' : 'merge_failed',
          details: merged ? 'Merged successfully' : 'Merge attempt failed',
        });
        if (merged) fetchPullRequests();
      } else {
        // If auto-merge is enabled but conditions not met, show a block toast.
        if (aiConfig.autoMergeEnabled) {
          console.log(`[AUTO-MERGE] ❌ NOT MERGING PR #${selectedPR.number}: cfg.enabled=${cfg.enabled}, finalWillMerge=${finalWillMerge}`);
          console.log(`  → ${reasonBase}`);
          console.log(`  → Decision: ${finalWillMerge ? 'SHOULD MERGE' : 'SHOULD NOT MERGE'}`);
          toast({
            title: 'Auto-Merge Not Triggered',
            description: 'Configured thresholds not met — posting review comment instead.',
          });
        }

        // Default behavior: post comment if configured
        if (aiConfig.postToGitHub && config) {
          const markdown = formatReviewAsMarkdown(review, selectedPR);
          await postPRComment(selectedPR.number, markdown);
        }
      }
    }

    if (results.thresholdCheck.exceeded) {
      toast({
        title: "Quality Gate Failed",
        description: `${results.thresholdCheck.violations.length} threshold violations detected`,
        variant: "destructive",
      });
    } else {
      toast({
        title: "Quality Gate Passed",
        description: "All quality thresholds met",
      });
    }
  }, [selectedPR, fetchPRFiles, analyzePR, mockSonarResults, generateReview, aiConfig, config, postPRComment, mergePR, fetchPullRequests]);

  const handleGenerateAIReview = useCallback(async (command: ReviewCommand) => {
    if (!selectedPR) return;
    
    const files = await fetchPRFiles(selectedPR.number);
    const review = await generateReview(selectedPR, files, command);
    
    if (review) {
      setAIReview(prev => prev ? { ...prev, ...review } : review);
    }
  }, [selectedPR, fetchPRFiles, generateReview]);

  const handlePostToGitHub = useCallback(async () => {
    if (!selectedPR || !aiReview) return;
    
    const markdown = formatReviewAsMarkdown(aiReview, selectedPR);
    await postPRComment(selectedPR.number, markdown);
  }, [selectedPR, aiReview, postPRComment]);

  const handleMergePR = useCallback(async () => {
    if (!selectedPR) return;
    
    const success = await mergePR(selectedPR.number, selectedPR.title);
    if (success) {
      fetchPullRequests();
    }
  }, [selectedPR, mergePR, fetchPullRequests]);

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 border-b border-border bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
        <div className="container flex h-16 items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="flex items-center gap-2">
              <Code2 className="h-6 w-6 text-primary" />
              <h1 className="text-xl font-bold">
                <span className="text-gradient">CodeGate</span>
                <span className="text-muted-foreground font-normal ml-2">Review</span>
              </h1>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {/* Quick actions for selected PR */}
            {selectedPR && aiReview && (
              <>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handlePostToGitHub}
                  disabled={!config}
                >
                  <MessageSquare className="mr-2 h-4 w-4" />
                  Post to GitHub
                </Button>
                {selectedPR.state === 'open' && (
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleMergePR}
                    disabled={!config}
                  >
                    <GitMerge className="mr-2 h-4 w-4" />
                    Merge PR
                  </Button>
                )}
                {/* Diagnostics Card */}
                <Card className="ml-4 hidden md:block">
                  <CardHeader>
                    <CardTitle className="text-sm">Auto-Merge Diagnostics</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="text-xs">
                      <div>AI Score: <span className="font-medium">{aiReview?.overallScore ?? '—'}</span></div>
                      <div>Sonar Issues: <span className="font-medium">{sonarResults?.issuesSummary?.total ?? '—'}</span></div>
                      <div>JUnit Score: <span className="font-medium">{junitScore ?? '—'}</span></div>
                      <div>Mode: <span className="font-medium">{aiConfig.autoMergeMode ?? 'less'}</span></div>
                      <div>AI Threshold: <span className="font-medium">{aiConfig.autoMergeThresholdAI ?? 70}</span></div>
                      <div>Sonar Threshold: <span className="font-medium">{aiConfig.autoMergeThresholdSonar ?? 5}</span></div>
                      <div className="pt-2">Decision: <span className="font-medium">
                        {(() => {
                          const aiScore = aiReview?.overallScore ?? 0;
                          const sonarIssues = sonarResults?.issuesSummary?.total ?? Infinity;
                          const mode = aiConfig.autoMergeMode || 'less';
                          const aiThreshold = aiConfig.autoMergeThresholdAI ?? 70;
                          const sonarThreshold = aiConfig.autoMergeThresholdSonar ?? 5;

                          if (!aiConfig.autoMergeEnabled) return 'Auto-merge disabled';
                          if (mode === 'less') {
                            return (aiScore < aiThreshold && sonarIssues < sonarThreshold) ? 'Will auto-merge' : 'Will NOT auto-merge';
                          }
                          return (aiScore > aiThreshold && sonarIssues > sonarThreshold) ? 'Will auto-merge' : 'Will NOT auto-merge';
                        })()}</span>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </>
            )}
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setIsDark(!isDark)}
            >
              {isDark ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}
            </Button>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="container py-6">
        <Tabs defaultValue="review" className="space-y-6">
          <TabsList className="grid w-full max-w-md grid-cols-3">
            <TabsTrigger value="review" className="gap-2">
              <Shield className="h-4 w-4" />
              Review
            </TabsTrigger>
            <TabsTrigger value="settings" className="gap-2">
              <Settings className="h-4 w-4" />
              Settings
            </TabsTrigger>
            <TabsTrigger value="webhook" className="gap-2">
              <Webhook className="h-4 w-4" />
              Webhook
            </TabsTrigger>
          </TabsList>

          {/* Review Tab */}
          <TabsContent value="review" className="space-y-6">
            {!config ? (
              <div className="max-w-2xl mx-auto">
                <GitHubConfigPanel
                  config={config}
                  onSave={setConfig}
                  onTest={testConnection}
                  isLoading={isLoading}
                />
              </div>
            ) : (
              <div className="grid grid-cols-12 gap-6">
                {/* PR List - Left Sidebar */}
                <div className="col-span-12 lg:col-span-3 h-[calc(100vh-12rem)]">
                  <PRList
                    pullRequests={pullRequests}
                    selectedPR={selectedPR}
                    onSelectPR={handleSelectPR}
                    onRefresh={fetchPullRequests}
                    isLoading={isLoading}
                  />
                </div>

                {/* Main Content Area */}
                <div className="col-span-12 lg:col-span-9 space-y-6">
                  {/* PR Details */}
                  <PRDetailPanel
                    pr={selectedPR}
                    sonarResults={sonarResults}
                    aiReview={aiReview}
                    onRunAnalysis={handleRunAnalysis}
                    isAnalyzing={isAnalyzing}
                    config={config}
                  />

                  {/* Analysis Results - Two Column Layout */}
                  {selectedPR && (
                    <div className="grid grid-cols-1 xl:grid-cols-2 gap-6">
                      <SonarResultsPanel
                        results={sonarResults}
                        isAnalyzing={isAnalyzing}
                        progress={analysisProgress}
                      />
                      <AIReviewPanel
                        pr={selectedPR}
                        review={aiReview}
                        onGenerateReview={handleGenerateAIReview}
                        isGenerating={isGeneratingAI}
                      />
                    </div>
                  )}
                </div>
              </div>
            )}
          </TabsContent>

          {/* Settings Tab */}
          <TabsContent value="settings" className="space-y-6">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
              <GitHubConfigPanel
                config={config}
                onSave={setConfig}
                onTest={testConnection}
                isLoading={isLoading}
              />
              <AIConfigPanel
                config={aiConfig}
                onSave={setAIConfig}
              />
            </div>
            <div className="max-w-2xl">
              <ThresholdConfigPanel
                thresholds={thresholds}
                onSave={setThresholds}
                aiConfig={aiConfig}
                onAIConfigSave={setAIConfig}
              />
            </div>
          </TabsContent>

          {/* Webhook Tab */}
          <TabsContent value="webhook" className="space-y-6">
            <WebhookInfoPanel config={config} />
          </TabsContent>
        </Tabs>
      </main>
    </div>
  );
}

function WebhookInfoPanel({ config }: { config: { owner: string; repo: string; webhookSecret?: string } | null }) {
  const webhookUrl = typeof window !== 'undefined' 
    ? `${window.location.origin}/api/webhook/github` 
    : '';

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied",
      description: "Copied to clipboard",
    });
  };

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      <div className="glass-card p-6 rounded-lg">
        <h2 className="text-xl font-semibold flex items-center gap-2 mb-4">
          <Webhook className="h-5 w-5" />
          GitHub Webhook Setup
        </h2>
        
        <div className="space-y-4">
          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-2">1. Webhook URL</h3>
            <div className="flex items-center gap-2">
              <code className="flex-1 p-3 rounded-lg bg-muted font-mono text-sm">
                {webhookUrl}
              </code>
              <Button variant="outline" size="sm" onClick={() => copyToClipboard(webhookUrl)}>
                Copy
              </Button>
            </div>
          </div>

          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-2">2. Content Type</h3>
            <code className="block p-3 rounded-lg bg-muted font-mono text-sm">
              application/json
            </code>
          </div>

          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-2">3. Events to Subscribe</h3>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1">
              <li>Pull requests</li>
              <li>Pull request reviews</li>
              <li>Pull request review comments</li>
              <li>Issue comments (for @ai commands)</li>
            </ul>
          </div>

          <div>
            <h3 className="text-sm font-medium text-muted-foreground mb-2">4. Secret</h3>
            <p className="text-sm text-muted-foreground mb-2">
              {config?.webhookSecret 
                ? "Webhook secret is configured. Use the same secret in GitHub."
                : "Configure a webhook secret in Settings for secure webhook verification."}
            </p>
          </div>

          {config && (
            <div className="pt-4 border-t border-border">
              <Button asChild>
                <a
                  href={`https://github.com/${config.owner}/${config.repo}/settings/hooks/new`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  <Github className="mr-2 h-4 w-4" />
                  Configure Webhook on GitHub
                </a>
              </Button>
            </div>
          )}
        </div>
      </div>

      <div className="glass-card p-6 rounded-lg">
        <h2 className="text-xl font-semibold flex items-center gap-2 mb-4">
          <Sparkles className="h-5 w-5" />
          AI Integration
        </h2>
        <p className="text-muted-foreground">
          Configure your AI provider in Settings to enable real AI-powered code reviews:
        </p>
        <ul className="list-disc list-inside text-sm text-muted-foreground mt-3 space-y-2">
          <li><strong>OpenAI</strong> - GPT-4o, GPT-4 Turbo</li>
          <li><strong>Anthropic</strong> - Claude Sonnet, Claude Haiku</li>
          <li><strong>Google AI</strong> - Gemini Pro, Gemini Flash</li>
          <li><strong>Groq</strong> - Free tier with Llama models</li>
        </ul>
        <p className="text-sm text-muted-foreground mt-4">
          Reviews can be automatically posted to GitHub PRs and PRs can be auto-merged if no major issues are found.
        </p>
      </div>
    </div>
  );
}